# render.yaml — FINAL VERSION FOR YOUR PROJECT
services:
  # PostgreSQL (Render free tier)
  - type: pgsql
    name: postgres
    plan: free
    region: oregon

  # Redis (Render free tier)
  - type: redis
    name: redis
    plan: free
    region: oregon

  # NGINX — your gateway
  - type: web
    name: nginx
    env: docker
    dockerfilePath: ./nginx/Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 80

  # Auth Service
  - type: web
    name: auth-service
    env: docker
    dockerfilePath: ./auth-service/Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: JWT_SECRET
        value: supersecretkey123
      - key: JWT_EXPIRES_IN
        value: 7d

  # Product Service (with Redis)
  - type: web
    name: product-service
    env: docker
    dockerfilePath: ./product-service/Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 3002
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: JWT_SECRET
        value: supersecretkey123
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: REDIS_URL
        fromService:
          name: redis
          type: redis
          property: connectionString   # Render gives redis://...:6379

  # Cart Service
  - type: web
    name: cart-service
    env: docker
    dockerfilePath: ./cart-service/Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 3003
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: JWT_SECRET
        value: supersecretkey123
      - key: JWT_EXPIRES_IN
        value: 7d

  # Order Service
  - type: web
    name: order-service
    env: docker
    dockerfilePath: ./order-service/Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 3004
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: JWT_SECRET
        value: supersecretkey123
      - key: JWT_EXPIRES_IN
        value: 7d